# Generated by Django 4.2.4 on 2023-09-03 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutcompmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField()),
                ('color', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='workoutcompmain.competition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participatingCompetitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
