# Generated by Django 4.2.5 on 2023-09-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0003_competition_users_delete_competitionuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='workouts',
            field=models.ManyToManyField(to='workoutcompmain.workout'),
        ),
    ]
