# Generated by Django 4.2.5 on 2023-09-15 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutcompmain', '0004_competition_workouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='workouts',
        ),
        migrations.AddField(
            model_name='workout',
            name='intensity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
