# Generated by Django 4.2.4 on 2023-09-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0007_alter_profile_color_alter_profile_restingheartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restingheartrate',
            field=models.IntegerField(default=0),
        ),
    ]
