# Generated by Django 4.2.4 on 2023-09-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0008_alter_profile_restingheartrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='owner',
        ),
    ]
