# Generated by Django 4.2.4 on 2023-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0009_remove_competition_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='note',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
