# Generated by Django 4.2.4 on 2024-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0010_workout_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='activity',
            field=models.TextField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.IntegerField(choices=[(1, 'Strength'), (2, 'Cardio'), (3, 'Wellness Activity'), (4, 'USP')]),
        ),
    ]
