# Generated by Django 5.0.1 on 2024-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0010_workout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.IntegerField(choices=[(1, 'Strength'), (2, 'Cardio'), (3, 'Wellness Activity'), (4, 'USP')]),
        ),
    ]
