# Generated by Django 4.2.4 on 2024-09-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0011_alter_workout_category'),
        ('workoutcompmain', '0011_workout_activity_alter_workout_category'),
    ]

    operations = [
    ]
