# Generated by Django 4.2.4 on 2024-09-29 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutcompmain', '0013_activity_activityvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityvote',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workoutcompmain.activity'),
        ),
        migrations.AlterField(
            model_name='activityvote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
