# Generated by Django 4.2.4 on 2024-09-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workoutcompmain', '0015_alter_activityvote_activity_alter_activityvote_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workoutcompmain.activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activityvote',
            unique_together={('activity', 'owner')},
        ),
    ]
