# Generated by Django 4.2.4 on 2024-09-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutcompmain', '0016_alter_workout_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='activityName',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
