name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: auth
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v3'
      with:
         registry: us-central1-docker.pkg.dev
         username: _json_key
         password: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workoutcomp-api .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workoutcomp-api

    - name: Deploy to Compute Engine
      run: |
        gcloud compute ssh workoutcomp-api --zone us-central1-f --command "docker pull us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workoutcomp-api && docker run -d -p 80:80 us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workoutcomp-api"
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
