name: Django CI

on:
  push:
    branches: [ "main", "test", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        CLIENT_ORIGIN_URL: http://localhost:3000
        AUTH0_DOMAIN: https://dev-mxnk6f4ep8oxln5o.us.auth0.com
        AUTH0_AUDIENCE: workoutcomp-api
        ENVIRONMENT: dev
        ALLOWED_HOSTS: localhost
      run: |
        python workoutcomp_api/manage.py test
